global:
  resolve_timeout: 5s

route:
  group_by: ['severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'mattermost'

receivers:
- name: 'mattermost'
  webhook_configs:
  - url: 'http://app:9001/alert'
